name: make hashbrowns 

on:
  push:
    paths:
      - 'dll/latest.dll'  # Specify the path to your latest.dll file
  workflow_dispatch:
jobs:
  check_hash:
    runs-on: ubuntu-latest

    steps:
      - name: cehckout repo
        uses: actions/checkout@v3

      - name: check if exists
        id: check_file
        run: |
          if [ ! -f "dll/latest.dll" ]; then
            echo "File latest.dll not found!"
            exit 1
          fi

      - name: get hash
        id: calculate_hash
        run: |
          sha256sum dll/latest.dll | awk '{ print $1 }' > output.txt

      - name: save  to file
        uses: actions/upload-artifact@v3
        with:
          name: output-hash
          path: dll_hash.txt
      - name: commit file with hashes (crazy)
        if: success()  
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add output.txt
          git commit -m "fix hash"
          
          
          git status
          
          git push
